version: '3'

networks:
  postgres-compose-network:
    driver: bridge

services:
  api-mks:
    build: .
    command: yarn start:dev
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
      - ./app:/usr/src/app/app
    # depends_on:
      # - postgres
      # - redis
    networks:
      - postgres-compose-network

  postgres:
    container_name: postgres-mks
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "SIrealmente28"
      POSTGRES_DB: "postgres"
    volumes:
      - .:/usr/app
      - ./app:/usr/src/app/app
    networks:
      - postgres-compose-network

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "caiosanttos43@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "SIrealmente28"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

  redis:
    container_name: redis-mks
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - .:/usr/app
      - ./app:/usr/src/app/app
    networks:
      - postgres-compose-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - postgres-compose-network
